org.gradle.jvmargs=-Xmx1G

# Fabric Properties
minecraft_version=26.1.2
loader_version=0.19.5
loom_version=1.17.20

# Mod Properties
mod_version=1.1.0
maven_group=dev.matejstastny
archives_base_name=servermatica

modrinth_compatible_versions = 26.1, 26.1.1, 26.1.2
modjson_compatible_versions = 26.1.2

# Dependencies
fabric_api_version=0.155.2+26.1.2
malilib_version=0.28.12
litematica_version=0.27.14
carpet_version=26.1
